### ISSUE TITLE
CT perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/nitroglycerin#13]
```
nitroglycerin : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 105488ms
Building runnable repository (nitroglycerin, brands: phet)
Building brand: phet
>> Webpack build complete: 21652ms
Fatal error: Perennial task failed:
Error: Unable to read "../nitroglycerin/nitroglycerin-strings_en.json" file (Error code: ENOENT).
at Object.util.error (/data/share/phet/continuous-testing/ct-snapshots/1658747812005/chipper/node_modules/grunt-legacy-util/index.js:55:39)
at Object.file.read (/data/share/phet/continuous-testing/ct-snapshots/1658747812005/chipper/node_modules/grunt/lib/grunt/file.js:224:22)
at Object.file.readJSON (/data/share/phet/continuous-testing/ct-snapshots/1658747812005/chipper/node_modules/grunt/lib/grunt/file.js:230:18)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1658747812005/chipper/js/grunt/reportUnusedStrings.js:50:57)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1658747812005/chipper/js/grunt/buildRunnable.js:141:3)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1658747812005/chipper/js/grunt/Gruntfile.js:280:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1658747812005/chipper/js/grunt/Gruntfile.js:56:7)
Full Error details:
Error: Unable to read "../nitroglycerin/nitroglycerin-strings_en.json" file (Error code: ENOENT).
Snapshot from 7/25/2022, 5:16:52 AM
```

**Comment by samreid** [comment]
Fixed, closing.

**Comment by pixelzoom** [comment]
Thanks for handling this @samreid.
